# book settings
title: Multi-Class classification examples
author: Kerry Pearn & Michael Allen

#only build files specified in table of contents file
only_build_toc_files: true

execute:
  execute_notebooks: off #cache output from .ipynb files for faster build
  timeout: -1 #no time restriction on notebook execution
  
launch_buttons:
  notebook_interface        : classic  
  binderhub_url             : ""
